name: CD for Hosting Code Base

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    # run for root and hosting
    paths-ignore:
      - "functions/**/*"
# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd hosting && flyctl deploy --remote-only
