name: CI for Hosting Code Base

on:
  pull_request:
    branches: ["main"]
# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install root deps
        run: npm ci --ignore-scripts
      - name: Install hosting deps
        run: cd hosting && npm ci --ignore-scripts && cd ..
      - name: Lint codebase with eslint
        run: npm run eslint:check -- hosting/
      - name: Lint codebase with prettier
        run: npm run prettier:check -- hosting/
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Build
        run: cd hosting && docker build -t docker-labs-hosting:latest .
      - name: Create tar
        run: docker save --output /tmp/docker-labs-hosting.tar docker-labs-hosting:latest
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-labs-hosting
          path: /tmp/docker-labs-hosting.tar
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-labs-hosting
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: docker tag docker-labs-hosting:latest foxt451/devops:latest && docker push foxt451/devops:latest
  test-curl:
    runs-on: ubuntu-latest
    needs: push
    steps: 
      - name: Pull image
        run: docker pull foxt451/devops:latest
      - name: Run image
        run: docker run -m 256m --cpus="2" -e PORT=80 -p 80:80 foxt451/devops:latest
      - name: Test curl
        run: curl http://localhost:80 --fail-with-body
