name: Lint and Build Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Lint codebase with eslint
        run: npm run eslint:check -- .
      - name: Lint codebase with prettier
        run: npm run prettier:check -- .
      - name: Build with typescript
        run: npm run build
